name: Web Audit Report
on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Runtime to execute report audit, values: npm | bun | pnpm | yarn'
        default: 'npm'
        required: true
        type: string
  schedule:
    - cron: '0 6 * * *' # â° Ejecuta todos los dÃ­as a las 6:00 AM UTC
env:
  REPORT_NAME: 'uppercase-object-keys'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ“¥ Clonar el repositorio
      uses: actions/checkout@v3
    - name: ğŸ”§ Instalar dependencias con npm ci
      run: npm ci
    - name: ğŸ§¨ Executing Script...
      run: curl https://raw.githubusercontent.com/ElJijuna/Bash-Scripts/refs/heads/main/web-audit-report.sh | bash -s ${{ inputs.runtime }} $REPORT_NAME
    - name: ğŸ“‚ Verify repository content
      run: ls -l
    - name: ğŸ“¦ Save report
      uses: actions/upload-artifact@v4
      with:
        name: audit-report
        path: ${{ env.REPORT_NAME }}--web-audit.json
  publish-report:
    runs-on: ubuntu-latest
    needs: audit
    steps:
    - name: ğŸ“¥ Cloning
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git clone --depth 1 https://x-access-token:${{ secrets.MONITORING_TOOL_DB }}@github.com/ElJijuna/MonitoringTool-DB.git .
    - name: ğŸ“¥ Download artifact
      uses: actions/download-artifact@v4
      with:
        name: audit-report
    - name: ğŸ“‚ Verify repository content
      run: ls -l
    - name: âœ… Commit & Push
      run: |
        git add ${{ env.REPORT_NAME }}--web-audit.json
        git commit -m "ğŸ“Š Update report"
        git push
